name: Good morning

on:
  schedule:
    # GitHub Actions cron uses UTC.
    # 16:00 UTC is 9am during Pacific daylight time.
    # 17:00 UTC is 9am during Pacific standard time.
    - cron: "0 16 * * *"
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  morning:
    runs-on: ubuntu-latest
    steps:
      - name: Say good morning
        run: |
          hour="$(TZ=America/Los_Angeles date +%H)"
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] || [ "$hour" = "09" ]; then
            echo "Good morning"
          fi
